### ISSUE TITLE
Preferred LNs seems to filter too widely

### ISSUE THREAD

**Issue by danyill** [danyill/oscd-subscriber-later-binding#10]
Preferred was set against only `PTRC` but for some reason `RBRF` was also mappable:

![image](https://user-images.githubusercontent.com/674783/234765622-eeade5b6-982e-4d75-ae61-5de0e399b1c8.png)

[test.zip](https://github.com/danyill/oscd-subscriber-later-binding/files/11339745/test.zip)

**Comment by jarradraumati** [comment]
I believe this is due to the cdc check. Some thoughts below:

I have a use case where a FCDA within a GOOSE dataset has the following:

```xml
<FCDA ldInst="HVCB" prefix="" lnClass="PTRC" lnInst="1" doName="Op" daName="general" fc="ST"/>
```

- DO = `Op`
- CDC = `ACT`
- DA = `general`
- bType = `BOOLEAN`

And an ExtRef I wish to subscribe:

```xml
<ExtRef desc="RxExtIn1" intAddr="RxExtIn1;/Ind/stVal" pServT="GOOSE" pDO="Ind" pDA="stVal"/>
```

- DO = `Ind`
- CDC = `SPS`
- DA = `stVal`
- bType = `BOOLEAN`

The subscribing IED in this example doesn't allow for the preferred pDO/pDA to be changed or removed from the `ExtRef` permanently. ICD files can be amended, but should an IID file be used from the ICT, it overrides the manual modifications to the preferred source.

If the `bType` between the publisher and subscriber is the same, technically I should be able to perform the subscription.

At present, the `doesFcdaMeetExtRefRestrictions` function doesn't allow for the subscription to succeed due to checking that the CDCs are the same.

```js
export function doesFcdaMeetExtRefRestrictions(extRef, fcda, controlBlockType) {
    // Vendor does not provide data for the check so any FCDA meets restriction
    if (!extRef.hasAttribute("pDO"))
        return true;
    const fcdaTypes = fcdaBaseTypes(fcda);
    const extRefSpec = extRefTypeRestrictions(extRef);
    // Check cannot be performed assume restriction check to fail
    if (!extRefSpec || !fcdaTypes)
        return false;
    if (extRef.getAttribute("pServT") &&
        controlBlockType !== extRef.getAttribute("pServT"))
        return false;
    if (extRef.getAttribute("pLN") &&
        extRef.getAttribute("pLN") !== fcda.getAttribute("lnClass"))
        return false;
    if (fcdaTypes.cdc !== extRefSpec.cdc)
        return false;
    if (extRef.getAttribute("pDA") && fcdaTypes.bType !== extRefSpec.bType)
        return false;
    return true;
```

I think this is overly restrictive, given we only have data attributes typically within a GOOSE/SV dataset, and we check `bType`s as a final confirmation we haven't tried to map something which isn't compatible.

I suggest that perhaps an option to disable the cdc check:

```js
if (fcdaTypes.cdc !== extRefSpec.cdc && !this.disableExtRefFCDACheck)
      return false;
```

Note that we probably need the option because this check is also done within the `tExtRef/subscribe` scl-lib function.
Thankfully, it has an override option which ignores the validation.
Although I think that check could also be refined as well so we don't completely eliminate the validation.

**Comment by danyill** [comment]
I'm a bit confused as to how the original issue relates to this feature request...

I thought the original issue was related to too many options available but this PR and your request seems to make more options available, not less.

It seems the menu item could be named "Ignore Common Data Class Check".

But I'm not sure that this is really a good option for the preconfigured workflow in IEC 61850-6:

In 9.3.13 of IEC 61850-6:

> A system configurator binding to these input templates must assure that the CDC specified by
> pDO and, if given, the attribute (base) type specified by pDA are met. For a final
> engineered data flow also the pServT, if given, shall be met by the serviceType value.

Perhaps it would be best to just have a menu option to completely disable preconfigured checks as a setting option rather than to hack with the intent of the standard (do this check but not that check)?

Otherwise I fear we need many options, perhaps even a whole "preferred" menu drop down (?) and the complexity of the plugin seems excessive:

* check preferred logical node class
* check preferred common data class
* check preferred basic type (but the standard is not clear, see Table 33 which states that the pDA check implies other checks I think)
* check preferred service type

**Comment by danyill** [comment]
@jakobvogelsang we would like to discuss this with you at some stage.

Basically it seems somewhat common to map common data class `ACT` onto common data class `SPS`.

Our scl-lib functionality `subscribe` doesn't allow this unless we use `force` (bypassing all other checks).

This oscd-subscriber-later-binding doesn't allow this without some changes (as per the linked PR).

Should we be able to bypass:

1. just the CDC check
2. any consideration of the pXX attributes at all
3. a more fine-grained set of options for the pXX attributes

I favour perhaps 2, but Jarrad is quite keen on 1.

As far as we can tell, DIGSI 5 does not enforce 1 for subscriptions (even if it places pXX attributes in the SCD file).

**Comment by danyill** [comment]
@JakobVogelsang agrees with only doing a basic type check (skipping LN, CDC). "Check only basic type match".

I'll file issue in scl-lib.

**Comment by danyill** [comment]
I can't reproduce this any more, so I think we can close this:

![image](https://github.com/danyill/oscd-subscriber-later-binding/assets/674783/6d1ade43-be5c-4258-adb4-50211f912239)
